#!/bin/bash

echo "VEXPro firmware programming and functional test -- launcher utility"
echo "Firmware" `cat ../version`

USB_SERIAL_DEVS0=`ls /dev/ttyUSB* 2>/dev/null`
while true
do 
   USB_SERIAL_DEVS1=`ls /dev/ttyUSB* 2>/dev/null`
   for i in $USB_SERIAL_DEVS1;
   do
      FOUND=0
      for j in $USB_SERIAL_DEVS0;
      do
         if [ "$i" = "$j" ];
         then
            FOUND=1
         fi
      done
      if [ $FOUND -eq 0 ];
      then
         echo "Launching" $i
	 gnome-terminal -e "./all $i" 
      fi
   done
      
   USB_SERIAL_DEVS0=$USB_SERIAL_DEVS1
   sleep .1
done