#!/bin/bash
PORT=`echo $1 | sed -e 's/^.*\(.\)$/\1/'`
PORT=$((PORT+1))
echo "VEXPro bootloader programming script"
echo
echo "Place jumper on J5."
echo "Plug in USB terminal and power into VEXPro."
echo "Then turn on."
if ../bin/download -t 9302 -p$PORT ../firmware/redboot.bin;
then
   echo
   echo "Power down."
   echo "Remove jumper from J5."
   exit 0
else
   exit 1
fi
