#!/bin/bash

echo "VEXPro firmware programming and functional test -- launcher utility"
echo "Firmware" `cat ../version`

USB_SERIAL_DEVS0=`ls /dev/ttyUSB* 2>/dev/null`
while true
do 
   USB_SERIAL_DEVS1=`ls /dev/ttyUSB* 2>/dev/null`
   for i in $USB_SERIAL_DEVS1;
   do
      FOUND=0
      for j in $USB_SERIAL_DEVS0;
      do
         if [ "$i" = "$j" ];
         then
            FOUND=1
         fi
      done
      if [ $FOUND -eq 0 ];
      then
         echo "Launching" $i
	 PORT=`echo $i | sed -e 's/^.*\(.\)$/\1/'`
	 X=$(((PORT%3)*280))
	 Y=$(((PORT/3)*140))
	 gnome-terminal --hide-menubar -e "./all $i" -t "$i" --geometry=39x6+$X+$Y 
      fi
   done
      
   USB_SERIAL_DEVS0=$USB_SERIAL_DEVS1
   sleep .1
done
