#!/bin/bash
# program bootloader
if bootloader;
then
   echo "Press enter to continue, q to quit."
   read INPUT
   if [ $INPUT = "q" ];
   then
      exit 1
   fi

   if program $1;
   then
       test $1	   
   fi
fi
     