#!/bin/sh
DAEMON=/opt/scripts/initializeTerkOS.pl
NAME=initializeTerkOS.pl
DESC="TerkOS Initializer"
ARGS=""

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
	echo -n "initializing FPGA... "
	/opt/bin/fpgac /opt/lib/vexpro.bit
        echo "done."
	echo -n "loading kernel modules... "
	modprobe qeinterrupt
	modprobe qemotor
	echo "done."
        echo -n "starting $DESC: $NAME... "
        start-stop-daemon -S -b -n $NAME -a $DAEMON -- $ARGS
        echo "done."
        ;;
    stop)
        echo -n "stopping $DESC: $NAME... "
        start-stop-daemon -K -n $NAME
        echo "done."
        ;;
    restart)
        echo "restarting $DESC: $NAME... "
        $0 stop
        $0 start
        echo "done."
        ;;
    reload)
        echo -n "reloading $DESC: $NAME... "
        killall -HUP $(basename ${DAEMON})
        echo "done."
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
        ;;
esac

exit 0
